### ISSUE TITLE
Improvements in cuesheet

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#133]
We should be looking at some improvements in the cuesheet based on user feedbak
- [ ] Event alarms #131 
- [ ] Countdown bar in cuesheet #130 
- [x] Follow selected should ignore past events #129
- [x] Revise style for past / current / future events #125 
- [x] Add table export #113 
- [x] Fullscreen view #156 
- [x] Resize all columns #156 

### Event Alarms
This needs to be workshopped further, I am unsure on what would this look like.
Where is the data displayed? How and where is the reminder time set?

### Countdown bar
This sounds pretty straigtforward. At least in theory. We should wait for the event redesign to see how it can help here

### Modify cuesheet styles
⛔ Won't do. The philosophy we follow here is that Cuesheet and Editor are integral for the application. Making this modifiable is detrimental to the development of the application since it adds an extra layer of maintenance

### Export
There is a user request for PDF export. While I believe this is a good feature, a CSV export feels like it gives a better feature set.
I am inclined to export a CSV of the table with this improvements and look into PDFs later. With the CSV the user gets a layer of control over the data and can use it in excel for printing.
It is an extra step, but I fear that the addition of PDFs will be followed with feature requests for restyling and branding which is not a priority as of now

**Comment by Keksstar** [comment]
#125 could also be part of this. Gray out the "played" events.

**Comment by cpvalente** [comment]
Closing this since we have separate issues to track the remaining actions
