### ISSUE TITLE
Create User ID for events

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#431]
### Why

Currently each event has a unique identifier generated on creation / import
We can also distinguish an event by its position in the rundown.

This means that our APIs allow us to interact with an event by using either of these fields like
```
/ontime/startid f6cac
/ontime/startindex 3
```

However, in the user workflows, we would need a static reference to an event that is more meaningful than the random id `f6cac`, but that does not depend on the runtime,
This is common practice in a cued system where a cue remains 101 even if 100.5 is added.

### TODO

The ticket task is to add an extra field to the event definition, which allows the user to provide an identifier to the field. 
This will be called cue in our datasets

The tasks is not particularly complex, but involves several parts of the code. We can aim to have smaller multiple pull requests that achieve the tasks defined rather than the entire feature description

The task would in short achieve:
- [ ] Add new cue field to OntimeEvent type and all its creation / parsing steps
- [ ] create API interfaces for this eg: /ontime/startcue (this would live in [dispatchFromAdapter](https://github.com/cpvalente/ontime/blob/master/apps/server/src/controllers/integrationController.ts#L5)
- [ ] create an editable field in the [EventEditor ](https://github.com/cpvalente/ontime/blob/master/apps/client/src/features/event-editor/EventEditor.tsx) for this, potentially where the ID is currently shown 
- [ ] investigate on how to present this in the editor view, could it go in the binder?
- [ ] add a new column in the cuesheet to show this

Some extra requirements:
- all events need to contain a cue, so we need to create one when an event is created 
- the cue value should be an increment on the previous value So after A1 we create A2, after Preshow 1 Preshow 2, and after NotNamed NotNamed 2
- once an event is running if an event is reordered and if a) we are in run mode: nothing changes b) we are in edit mode: we rename the event following the convention above

The [current event definition is here](https://github.com/cpvalente/ontime/blob/master/packages/types/src/definitions/core/OntimeEvent.type.ts#L27)

**Comment by cpvalente** [comment]
Implemented in #473
