### ISSUE TITLE
Component improvements in event block

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#55]
We are planning some work on restructuring some of the components. Mostly focusing on the usability of the app rather than adding new functionality

I thought it would be good to start a documentation on this, focusing for now on Event block which is next in line in worklist

- [x] Improve time input workflow, lots of good stuff at #50 and #46
- [ ] Show a small progressbar in running event when collapsed 
- [ ] Add playbutton to event block
- [ ] Add skip action #172 
- [ ] Allow more text to be added in notes (note field is text area) #59 
- [ ] Add a note event: event with a single text field and time without duration. eg: 08:30 mic check.
- [ ] Ability to link event times
- [ ] Visually diferentiate past and upcoming events #125 

and some aesthetic stuff
- [x] inconsistent border radius, see #53 
- [x] use nore space in event list, see #57 

will also have to match styles to the other blocks, this should be mostly styling, but while we are here
- [ ] delay field is maxed at 60, however this correction only happens on submit and not onBlur 
- [ ] When creating an event with the sortcut Alt+E, the option "Start time is last end" is not respected #171 

### Show a small progressbar in running event when collapsed 
User request. In half window mode the app shows only the eventlist. Some people like using this and triggering events remotely. It would be nice to have a clearer indication of which component is running and its progress

### Add playbutton to event block
User request. It would be nice to be able to trigger an event straight from its definition. I am assuming this is for people who use ontime as a stage timer application rather than a rundown list

### Add a note event
User request. One of the oldest things in the list. Some workflows would benefit from having a simpler event type for things without a duration. eg: 08:30 Mic check Michael Fassbender.

### Ability to link event times
We are looking at a possible workflow where the time start of an event could be linked to the end of another.
eg; event two would have as start time a link to its previous event and a duration of 30min. 
This could significantly complicate the usability and clutter the interface with advanced features if not approached correctly

**Comment by xztraz** [comment]
add the text "delay" to delay-box.  so it says    "$$ minutes delay" 

![image](https://user-images.githubusercontent.com/25690871/146647325-7f412bbc-8612-4efe-8b0c-13dc847a877f.png)

**Comment by xztraz** [comment]
Ability to link times, could in gui be as simple as just having a default end-time as the text "next" or a minus sign or alike. and if pushing it it assumes you want to enter something. no clutter.
![image](https://user-images.githubusercontent.com/25690871/146647672-87caea2b-2624-49ed-9694-d6daf7014427.png)

**Comment by cpvalente** [comment]
Closing this as mostly implemented in v2
